# Generated by Django 4.2 on 2026-04-26 20:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('page_path', models.CharField(blank=True, default='', max_length=512)),
                ('user_id', models.CharField(blank=True, default='', max_length=64)),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type', 'created_at'], name='metrics_eve_event_t_3b24a8_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['page_path', 'created_at'], name='metrics_eve_page_pa_9f9f8a_idx'),
        ),
    ]
