# Generated by Django 4.2.29 on 2026-04-30 19:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('page_path', models.CharField(blank=True, default='', max_length=512)),
                ('user_id', models.CharField(blank=True, default='', max_length=64)),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='metrics_eve_event_t_cd1539_idx'), models.Index(fields=['page_path', 'created_at'], name='metrics_eve_page_pa_881321_idx')],
            },
        ),
    ]
