# Generated by Django 4.2.29 on 2026-05-25 10:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(max_length=100)),
                ('career_stage', models.CharField(max_length=100)),
                ('current_goal', models.JSONField(default=list)),
                ('track_interest', models.CharField(max_length=100)),
                ('career_priority', models.CharField(max_length=100)),
                ('start_timeline', models.CharField(max_length=100)),
                ('info_call_availability', models.CharField(max_length=20)),
                ('preferred_contact_method', models.CharField(max_length=50)),
                ('source_channel', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('gdpr_consent', models.BooleanField(default=False)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('lead_status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20)),
                ('lead_type', models.CharField(choices=[('participant', 'Participant Lead'), ('mentor', 'Mentor Lead'), ('partner', 'Partner Lead'), ('institutional', 'Institutional Lead'), ('general', 'General Lead')], default='general', max_length=20)),
                ('lead_score', models.IntegerField(default=0)),
                ('lead_temperature', models.CharField(choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], default='cold', max_length=10)),
                ('source_page', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'db_table': 'leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
