# Generated by Django 4.2.29 on 2026-07-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='average_rating',
            field=models.DecimalField(db_index=True, decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='hourly_rate',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
