# Generated by Django 4.2.29 on 2026-07-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='scheduled_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['mentor', 'scheduled_at'], name='sessions_mentor__01f2ab_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['mentor', 'status', 'scheduled_at'], name='sessions_mentor__4e330c_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['mentee', '-created_at'], name='sessions_mentee__c060b2_idx'),
        ),
    ]
