# Generated by Django 4.2.29 on 2026-07-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship_sessions', '0002_alter_session_scheduled_at_alter_session_status_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed'])), fields=('mentor', 'scheduled_at'), name='unique_active_session_slot'),
        ),
    ]
